### ISSUE TITLE
Switching tabs decreased my seed storage max

### ISSUE THREAD

**Issue by XarsYs** [Mezeman1/idle-ant-farm#35]
I am after 1 prestige, bought 3 (prestige) storage upgrades, then during my run my seed max was at 1.7 million at a point, but after I switched browser tab and came back the cap is now at 429k which I would guess doesn't account for some upgrade I have somewhere.

**Comment by steve2116** [comment]
Do you know if you got back the prestige points/seeds you spent on the upgrade? The game only saves every minute or so and switching tabs is like refreshing the page.

I think it could be you (or if you have auto seed storage) buying seed storage, and then when you switched tab it undid the upgrades bought since the game last saved.

**Comment by Mezeman1** [comment]
I think I have fixed this, but let me know if not.

**Comment by XarsYs** [comment]
After switching browser tabs, my maximum seed amount still reduces (the first time I do it after a fresh prestige).
Save string if it helps for any reason:
[antSave.txt](https://github.com/user-attachments/files/17081709/antSave.txt)

**Comment by XarsYs** [comment]
I checked again, and it seems to work now with the same steps. Either the update was not live at my first recheck, or it was fixed later. Just letting you know so there is no unnecessary bug analysis.
